### PR TITLE
Update Firefox Browser script on Mac

### PR DESCRIPTION
**Pull request by davidhenley**
Added spaces as this is how it downloads and extracts to Mac

### CODE REVIEW

**Comment by wesbos** [comment]
Hmm - this breaks it for me. Which version of OSX are you on?

**Comment by davidhenley** [comment]
Latest. 10.13.2 and just downloaded newest Firefox Dev 30 minutes ago.

*David Henley*
615-438-3334

**Comment by wesbos** [comment]
You're right - they now make it with spaces. I'll merge this and add a FAQ

**Comment by davidhenley** [comment]
Awesome, My first pull request! Thanks!

**Comment by wesbos** [comment]
Woooo woooooooooooooo congrats

**Pull request merged**
